services:
  horizon:
    extends:
      file: app.yml
      service: app
    image: ${PROJECT_ALIAS}-app:latest
    restart: always
    entrypoint: [ "php", "artisan", "horizon" ]
    networks:
      container_network:
        ipv4_address: ${NETWORK_SUBNET}.98
